Fix bug (#16)
* Fix bug

When running tar-progress I had the following error:
Traceback (most recent call last):
  File "/home/user/.local/bin/tar-progress", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.9/site-packages/tar_progress/__main__.py", line 51, in main
    archiver.create(arguments.file, arguments.compressor, arguments.files)
  File "/home/user/.local/lib/python3.9/site-packages/tar_progress/classes/linux.py", line 38, in create
    command = "tar -cf - " + files + " | pv -s " + size + " | bzip2 > " + filename
TypeError: can only concatenate str (not "bytes") to str

Which arose since there is no implicit conversion between bytes and strings.

* Remove unsupported python version (2.7)